# Kubernetres kubectl configuration file for the MC project,
# to produce the MC server in a container.
# © Copyright Benedict Adamson 2019-20.
#
# This file is part of MC.
#
# MC is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with MC.  If not, see <https://www.gnu.org/licenses/>.
#
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: MC
  ports:
  - protocol: TCP
    port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  selector:
    app: MC
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  selector:
    app: MC
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mc-db-root-pasword-secret
type: Opaque
stringData:
  db-password: FIXME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-fe-config
data:
  httpd-local.conf: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MC
  template:
    metadata:
      name: db
      labels:
        app: MC
    spec:
      containers:
      - name: mc-db
        image: mongo:4
        args:
        - --bind_ip
        - 0.0.0.0
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 11
          periodSeconds: 3
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mc-db-root-pasword-secret
              key: db-password
        volumeMounts:
        - mountPath: /data/db
          name: mc-data-db
        - mountPath: /var/secrets
          name: mc-db-secrets
          readOnly: true
      volumes:
      - name: mc-db-secrets
        secret:
          secretName: mc-db-root-pasword-secret
      - name: mc-data-db
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MC
  template:
    metadata:
      name: be
      labels:
        app: MC
    spec:
      containers:
      - name: mc-back-end
        image: benedictadamson/mc-back-end:2.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        args:
        - --spring.data.mongodb.host=db
        - --spring.data.mongodb.username=admin
        env:
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mc-db-root-pasword-secret
              key: db-password
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 13
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 59
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MC
  template:
    metadata:
      name: fe
      labels:
        app: MC
    spec:
      containers:
      - name: mc-front-end
        image: benedictadamson/mc-front-end:2.0.1-SNAPSHOT
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /config
          name: mc-fe-config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 13
      volumes:
      - name: mc-fe-config
        configMap:
          name: mc-fe-config