#!/bin/sh
# missioncommand-db .deb postinst

MODE="$1"
shift
case "$MODE" in
configure) # preinst was successful and files have been unpacked
  if [ $# -gt 0 ]; then
    # upgrading, or installing from the "Config Files" state
    # (package was installed, then removed, but not purged)
    OLD_VERSION="$1"
    shift
    HAVE_CONFIG_FILES=Y
  else
    HAVE_CONFIG_FILES=N
  fi
  if which systemctl > /dev/null; then
    # a systemd installation (rather than Docker)
    /usr/share/missioncommand-db/bin/init-mc
  else
    # do not need conf files used by systemd installation
    rm /etc/mission-command/mongodb-admin-psswd.secret
    rm /etc/mission-command/mongodb-mc-psswd.secret
  fi
  ;;
abort-upgrade) # "prerm upgrade" failed during an upgrade
  NEW_VERSION="$1"
  shift
  # Do nothing
  ;;
abort-remove) # "prerm remove" failed during a remove or remove+purge
  NEW_VERSION="$1"
  shift
  # Do nothing
  ;;
*)
  echo "unrecognised postinst mode \"$MODE\"" 1>&2
  exit 2;;
esac