#!/bin/sh
# missioncommand-db .deb prerm

MODE="$1"
shift
case "$MODE" in
remove) # removal or removal+purge
  # Do nothing
  ;;
upgrade)
  NEW_VERSION="$1"
  shift
  # Do nothing
  ;;
*)
  echo "unrecognised prerm mode \"$MODE\"" 1>&2
  exit 2;;
esac