#!/bin/sh
# mkminikubeinstall
# Create a minikube instance with mc installed using Docker images in the local registry
#
# SYNOPSIS
# mkminikubeinstall <version> <package>
#
# COMMAND LINE ARGUMENTS
# <version>
# The version of MC to install
# <package>
# The path-name or name of the Helm package to install.
#
# ENVIRONMENT
# The minikube program must be in the program search PATH.
# The helm program must be in the program search PATH.

# Read environment
TMPDIR="${TMPDIR:-/var/tmp}"

# Enable clean handling of temporary files
TMPDIR="$TMPDIR/mkminikubeinstall-$$"
mkdir "$TMPDIR"
export TMPDIR
rmTmpdir () {
  rm -rf "$TMPDIR"
}
trap rmTmpdir EXIT

# Parse command-line arguments
VERSION="$1"
PACKAGE="$2"

# Start minikube
VM="k8-mc-$VERSION"
minikube start \
  --profile="${VM}" \
  --delete-on-failure=true \
  --memory=4g \
  --addons ingress

# Upload the local Docker images
# (minikube will only fetch from public registries or using loaded images,
# never from our local registry)

loadDockerImage () {
  echo "loading Docker image for $1"
  minikube image load "--profile="${VM}" benedictadamson/$1:$VERSION"
}
  
loadDockerImage awaitport
loadDockerImage mc-back-end
loadDockerImage mc-database
loadDockerImage mc-front-end-srv

echo "installing Helm package"
helm install -g --timeout 600s "${PACKAGE}"